// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  hero: dynamic(() => import("./Hero")),
  newsletter: dynamic(() => import("./Newsletter")),
  footer_columns: dynamic(() => import("./FooterColumns")),
  copyright: dynamic(() => import("./Copyright")),
};
